version: "3.8"

services:
  db_service:
    image: mysql:8.0
    container_name: db_penyewaan_motor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: penyewaan_motor
      MYSQL_USER: rayhan
      MYSQL_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - penyewaan_motor_network

  app_service:
    build: ./app
    container_name: app_penyewaan_motor
    restart: always
    expose:
      - "3000"
    environment:
      DB_HOST: db_service
      DB_USER: rayhan
      DB_PASS: password123
      DB_NAME: penyewaan_motor
      APP_PORT: 3000
    depends_on:
      - db_service
    networks:
      - penyewaan_motor_network

  nginx_service:
    image: nginx:alpine
    container_name: nginx_penyewaan_motor
    restart: always
    ports:
      - "2562:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - penyewaan_motor_network

volumes:
  db_data: 

networks:
  penyewaan_motor_network:
    driver: bridge
